[DB]
	[DB.test]                                       # DB组名称:test
		[DB.test.Master]                            # Master配置
			dialect = "mysql"                       # DB类型:mysql
			dsn = "root:wwww@tcp(127.0.0.1:10110)/dcmc?parseTime=true&loc=Local&charset=utf8mb4,utf8"      # 地址
			maxOpenConns = 100                      # 最大连接数
			maxIdleConns = 50                       # 最大空闲连接数
			connMaxLifetime = 300                   # 最大空闲回收时间，单位：s
			logMode = true                          # 是否开启debug日志
			logSQL =true                            # 是否显示日志中的sql
			slowThreshold = 500                     # 慢日志阈值，单位：ms
		[DB.test.Slave]                             # Slave配置
			dialect = "mysql"
			dsn = ["root:wwww@tcp(10.20.22.119:10110)/dcmc?parseTime=true&loc=Local&charset=utf8mb4,utf8", "root:wwww@tcp(10.20.22.119:10110)/dcmc?parseTime=true&loc=Local&charset=utf8mb4,utf8"]
			maxOpenConns = 100
			maxIdleConns = 50
			connMaxLifetime = 300
			logMode = true
			logSQL =true
			slowThreshold = 500
